# Generated by Django 5.2.4 on 2026-01-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('file_type', models.CharField(choices=[('extracted', 'Extracted'), ('attached', 'Attached')], max_length=50)),
                ('file_name', models.CharField(max_length=500)),
                ('file_location', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
