# Generated by Django 5.2.4 on 2026-01-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_format',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
