# Generated by Django 5.2.4 on 2026-01-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_file_file_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=5000)),
            ],
        ),
    ]
